### ISSUE TITLE
Car Accessories Page

### ISSUE THREAD

**Issue by falansari** [falansari/car_reservation_system_web#19]
- [x] Redirect to it when user clicks on "Proceed with Reservation" button in #8  Create Reservation Page.
- [x] Retrieve car id from get request from #8 .
- [x] Allows selecting multiple accessories.
- [x] Each accessory with checkbox for selecting multiple.
- [x] "Skip" button for not adding any accessories. Redirect to #55  with car id only.
- [x] "Add Accessories" button. Passes car id & chosen accessories to #55.
- [x] "Cancel" button. Redirects back to #7 .
