### ISSUE TITLE
Create Reservation Page

### ISSUE THREAD

**Issue by falansari** [falansari/car_reservation_system_web#8]
- [x] Page accessible from clicking “Book Now” buttons on individual listings in #43  Search results page.
- [x] Pre-Populated fields: Selected car in booking.
- [x] Display full car info:
  - [x] Image
  - [x] Manufacturer
  - [x] Model
  - [x] Make year
  - [x] Category
  - [x] Daily rental price
- [x] “Cancel” button. Redirects to #7 homepage.
- [x] “Proceed With Booking” button to direct to #19 Car accessories page. Pass car id.
