### ISSUE TITLE
Checkout Page

### ISSUE THREAD

**Issue by falansari** [falansari/car_reservation_system_web#9]
- [x] Redirected here from #55  Reservation Customer Details Page.
- [x] Show full summary of booking details passed in from #55.
- [x] Show total cost based on cars’ total daily price * days booked.
- [x] “Cancel” button. Discard reservation and redirect back to #7 homepage.
- [x]  “Confirm” button. Direct to #10 Payment page. Pass car id, any chosen accessories ids, start and end dates, total cost (full reservation data).
